version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    parameters:
      triplet:
        type: string
        default: "x64-windows"
      features:
        type: string
        default: "core"
    executor:
      name: win/default
    environment:
      VCPKG_DISABLE_METRICS: 1
    steps:
      - run:
          name: choco install
          command: |
            choco install cmake -y -r --no-progress --installargs 'ADD_CMAKE_TO_PATH=System'
            choco install ninja -y -r --no-progress
            $env:PATH
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: vcpkg bootstrap
          command: ./vcpkg/bootstrap-vcpkg.bat
      - restore_cache:
          key: vcpkg-cache-{{ checksum "VCPKG_HASH.txt" }}-<< parameters.triplet >>-<< parameters.features >>
      - run:
          name: vcpkg upgrade
          command: |
            ./vcpkg/vcpkg.exe upgrade --no-dry-run
            ./vcpkg/vcpkg.exe install ffmpeg[<< parameters.features >>]:<< parameters.triplet >> --recurse
          no_output_timeout: 60m
      - save_cache:
          key: vcpkg-cache-{{ checksum "VCPKG_HASH.txt" }}-<< parameters.triplet >>-<< parameters.features >>
          paths:
            - vcpkg/installed
      - run:
          name: ffmpeg features
          command: |
            $env:ALL_FEATURES = (((./vcpkg/vcpkg.exe list | Select-String -Pattern "ffmpeg\[(.*)\]:<< parameters.triplet >>\s") -Replace "ffmpeg\[(.*)\]:.*","`$1") + "core") -Join ";"
            $env:ALL_FEATURES
            $env:MSVC_RUNTIME_LIBRARY = if ("<< parameters.triplet >>".EndsWith("-static")) { "MultiThreaded" } else { "MultiThreadedDLL" }
            $env:MSVC_RUNTIME_LIBRARY
      - run:
          name: build test
          command: |
            $env:TRIPLET = "<< parameters.triplet >>"
            ./build-test.bat
workflows:
  version: 2
  weekly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
  manual:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
