version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: systeminfo
      - run:
          name: Build
          command: |
            $triplet = "x64-windows"
            $features = "core,avcodec"
            $vcpkg = Get-Content .\VCPKG_HASH.txt -Encoding Ascii
            cd .\vcpkg\
            .\bootstrap-vcpkg.bat -disableMetrics
            .\vcpkg.exe integrate install
            .\vcpkg.exe upgrade --no-dry-run
            .\vcpkg.exe install ffmpeg[${features}]:${triplet} --recurse
            dir /s /b "installed\${triplet}"
            $all_features = (.\vcpkg.exe list | Select-String -Pattern "ffmpeg\[(.*)\]:${env:TRIPLET}\s") -Replace "ffmpeg\[(.*)\]:.*","`$1" -Join ";"
            echo "all features = ${all_features}"
            cd ..
            mkdir build-rel
            cd build-rel
            cmake ../test -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${triplet} -DFEATURES=${all_features} -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL
            cmake --build .
            ctest -V
