version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
    environment:
      TRIPLET: x64-windows
      FEATURES: core
      MSVC_RUNTIME_LIBRARY: MultiThreadedDLL
    steps:
      - run: choco install cmake
      - run: dir "C:\Users\circleci\thirdparty"
      - run: cmake
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: .\vcpkg\bootstrap-vcpkg.bat
      - run:
          name: vcpkg upgrade
          command: .\vcpkg.exe upgrade --no-dry-run
          no_output_timeout: 60m
      - run:
          name: vcpkg install ffmpeg
          command: .\vcpkg.exe install ffmpeg[${env:FEATURES}]:${env:TRIPLET} --recurse
          no_output_timeout: 60m
      - run:
          name: vcpkg extract features
          command: |
            $env:ALL_FEATURES = (.\vcpkg\vcpkg.exe list | Select-String -Pattern "ffmpeg\[(.*)\]:${env:TRIPLET}\s") -Replace "ffmpeg\[(.*)\]:.*","`$1" -Join ";"
            echo "${env:ALL_FEATURES}"
      - run:
          name: test release
          command: |
            mkdir build-rel
            cd build-rel
            cmake ../test -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${env:TRIPLET} -DFEATURES=${env:ALL_FEATURES} -DCMAKE_MSVC_RUNTIME_LIBRARY=${env:CMAKE_MSVC_RUNTIME_LIBRARY}
            cmake --build .
            ctest -V
