version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build:
    executor:
      name: win/default
    environment:
      TRIPLET: x64-windows
      FEATURES: core
    steps:
      - checkout
      - run: systeminfo
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install vcpkg
          command: |
            cd .\vcpkg\
            & .\bootstrap-vcpkg.bat
            & .\vcpkg.exe integrate install
            cd ..
      - run:
          name: Build
          no_output_timeout: 60m
          command: |
            cd .\vcpkg\
            & .\vcpkg.exe upgrade --no-dry-run
            & .\vcpkg.exe install ffmpeg[${env:FEATURES}]:${env:TRIPLET} --recurse
            dir /s /b "installed\${env:TRIPLET}"
            cd ..
      - run:
          name: Test
          command: |
            $all_features = (.\vcpkg\vcpkg.exe list | Select-String -Pattern "ffmpeg\[(.*)\]:${env:TRIPLET}\s") -Replace "ffmpeg\[(.*)\]:.*","`$1" -Join ";"
            echo "all features = ${all_features}"
            mkdir build-rel
            cd build-rel
            cmake ../test -G Ninja -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=${env:TRIPLET} -DFEATURES=${all_features} -DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreadedDLL
            cmake --build .
            ctest -V
