version: 2.1
orbs:
  win: circleci/windows@2.2.0
jobs:
  build_linux:
    parameters:
      triplet:
        type: string
        default: "x64-linux"
      features:
        type: string
        default: "core"
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - run: sudo apt-get install cmake ninja-build
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: vcpkg bootstrap
          command: ./vcpkg/bootstrap-vcpkg.sh -disableMetrics -useSystemBinaries
      - restore_cache:
          key: vcpkg-cache-{{ checksum "VCPKG_HASH.txt" }}-<< parameters.triplet >>-<< parameters.features >>
      - run:
          name: vcpkg upgrade
          command: |
            ./vcpkg/vcpkg upgrade --no-dry-run
            ./vcpkg/vcpkg install ffmpeg[<< parameters.features >>]:<< parameters.triplet >> --recurse
          no_output_timeout: 60m
      - save_cache:
          key: vcpkg-cache-{{ checksum "VCPKG_HASH.txt" }}-<< parameters.triplet >>-<< parameters.features >>
          paths:
            - vcpkg/installed
      - run:
          name: test
          command: |
            ./test.sh `pwd`/vcpkg << parameters.triplet >>
  build_windows:
    parameters:
      triplet:
        type: string
        default: "x64-windows"
      features:
        type: string
        default: "core"
    executor:
      name: win/default
    environment:
      VCPKG_DISABLE_METRICS: 1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: vcpkg bootstrap
          command: ./vcpkg/bootstrap-vcpkg.bat
      - restore_cache:
          key: vcpkg-cache-{{ checksum "VCPKG_HASH.txt" }}-<< parameters.triplet >>-<< parameters.features >>
      - run:
          name: vcpkg upgrade
          command: |
            ./vcpkg/vcpkg.exe upgrade --no-dry-run
            ./vcpkg/vcpkg.exe install ffmpeg[<< parameters.features >>]:<< parameters.triplet >> --recurse
          no_output_timeout: 60m
      - save_cache:
          key: vcpkg-cache-{{ checksum "VCPKG_HASH.txt" }}-<< parameters.triplet >>-<< parameters.features >>
          paths:
            - vcpkg/installed
      - run:
          name: test
          command: |
            ./test.bat C:\Users\circleci\project\vcpkg << parameters.triplet >>
workflows:
  version: 2
  weekly:
    jobs:
      - build_windows
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only:
                - master
  manual_windows:
    jobs:
      - hold_windows:
          type: approval
      - build_windows:
          requires:
            - hold_windows
  manual_linux:
    jobs:
      - hold_linux:
          type: approval
      - build_linux:
          requires:
            - hold_linux
