name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        triplet: [x64-linux, x64-osx]
        features_id: [minimal, release, ffmpeg]
        include:
          - triplet: x64-linux
            os: ubuntu-latest
          - triplet: x64-osx
            os: macos-latest
          - features_id: minimal
            features: "[core]"
          - features_id: release
            features: "[core,avcodec,avformat,avdevice,avfilter,swresample,swscale,opus,vpx]"
          - features_id: ffmpeg
            features: "[core,ffmpeg]"
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 1  # to avoid running out of memory
      VCPKG_MAX_CONCURRENCY: 1  # to avoid running out of memory
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install ubuntu dependencies
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install cmake ninja-build nasm gperf libgl-dev libxext-dev

      - name: Install macos dependencies
        if: ${{ matrix.os == 'macos-latest' }}
        run: brew install cmake ninja nasm

      - uses: actions/cache@v2
        id: vcpkg-executable-cache
        with:
          path: ./vcpkg/vcpkg
          key: vcpkg-${{ runner.os }}

      - name: Bootstrap vcpkg
        if: steps.vcpkg-executable-cache.outputs.cache-hit != 'true'
        run: ./vcpkg/bootstrap-vcpkg.sh -disableMetrics -useSystemBinaries

      - uses: actions/cache@v2
        id: vcpkg-installed-cache
        with:
          path: ./vcpkg/installed
          key: vcpkg-${{ hashFiles('VCPKG_HASH.txt') }}-${{ matrix.triplet }}-${{ matrix.features_id }}

      - name: Install ffmpeg
        if: steps.vcpkg-installed-cache.outputs.cache-hit != 'true'
        run: ./vcpkg/vcpkg install ffmpeg${{ matrix.features }}:${{ matrix.triplet }} --recurse

      - name: Test
        run: ./test.sh $GITHUB_WORKSPACE/vcpkg ${{ matrix.triplet }}
  
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: ./vcpkg/buildtrees/**/*.logs
