name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        triplet: [x64-linux]
        features: ["core", "all,all-gpl,all-nonfree"]
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 1  # to avoid running out of memory
      VCPKG_MAX_CONCURRENCY: 1  # to avoid running out of memory
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt-get install cmake ninja-build nasm gperf libgl-dev libxext-dev

      - uses: actions/cache@v2
        id: vcpkg-executable-cache
        with:
          path: ./vcpkg/vcpkg
          key: vcpkg-${{ runner.os }}

      - name: Bootstrap vcpkg
        if: steps.vcpkg-executable-cache.outputs.cache-hit != 'true'
        run: ./vcpkg/bootstrap-vcpkg.sh -disableMetrics -useSystemBinaries

      - uses: actions/cache@v2
        id: vcpkg-installed-cache
        with:
          path: ./vcpkg/installed
          key: vcpkg-${{ runner.os }}-${{ hashFiles('VCPKG_HASH.txt') }}-${{ matrix.triplet }}-${{ matrix.features }}

      - name: Install ffmpeg
        if: steps.vcpkg-installed-cache.outputs.cache-hit != 'true'
        run: ./vcpkg/vcpkg install ffmpeg[${{ matrix.features }}]:${{ matrix.triplet }} --recurse

      - name: Test
        run: ./test.sh $GITHUB_WORKSPACE/vcpkg ${{ matrix.triplet }}
